env:
  browser: true
  node: true
  es2021: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

settings:
  react:
    version: detect

rules:
  # Turn off rules
  '@typescript-eslint/no-empty': off
  '@typescript-eslint/no-var-requires': off

  # Set some rules from error to warining
  '@typescript-eslint/no-empty-function': warn
  '@typescript-eslint/no-unused-vars': warn
  prefer-const: warn

  # Coding styles
  indent: [warn, 2, { SwitchCase: 1 }]
  semi: [warn, never]
  quotes: [warn, single]
  comma-dangle: [warn, always-multiline]