env:
  browser: true
  node: true
  es2021: true

plugins:
  - react
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

rules:
  no-unused-vars: 'off'
  no-empty: warn
  no-empty-function: 'off'
  '@typescript-eslint/no-empty-function': warn

  semi: [warn, never]
  quotes: [warn, single]
  comma-dangle: [warn, never]
  indent: [warn, 2, { SwitchCase: 1 }]