env:
  browser: true
  node: true
  es2021: true

extends:
  - eslint:recommended
  - eslint:react/recommended
  - '@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'

rules:
  no-unused-vars: warn
  no-empty: warn

  semi: [warn, never]
  quotes: [warn, single]
  comma-dangle: [warn, never]
  indent: [warn, 2, { SwitchCase: 1 }]