# These configurations would be used by both frontend and backend

# Server port
port: 17777

# Development mode
dev: false

# Port for frontend in development mode
devport: 16666

# Title for frontend homepage
title: monurls