# These configurations would only be used by backend

# Secret of cookie signature
secret: wut

# Fastify logging level, see below
# https://www.fastify.io/docs/latest/Reference/Logging/
# https://github.com/pinojs/pino/blob/master/docs/api.md#logger-level
logger: 'info'

# Database settings (mariadb)
db:
  # Database host
  host: localhost

  # Database port
  port: 3306

  # Database name
  database: monurls

  # User who can use the database above
  user: user

  # Password of the user
  password: password

# Valid keys when logging in
key:
  - wut